detectors:
  IrresponsibleModule:
    enabled: false
  FeatureEnvy:
    exclude:
      - 'SetupGame' # interactors deal on stateful object - state, therefore could be feature envies
  Attribute:
    exclude:
      - 'State' # State is to be operated on
  TooManyStatements:
    exclude:
      - 'SetupGame#validate' # validation is about raising errors if something is invalid
