detectors:
  IrresponsibleModule:
    enabled: false
  FeatureEnvy:
    exclude:
      # interactors deal on stateful object - state, therefore could be feature envies
      - 'SetupGame'
      - 'SettleWithRoad'
  Attribute:
    exclude:
      - 'State' # State is to be operated on
      - 'Resources' # Needed to do clever meta-programming
  TooManyInstanceVariables:
      exclude:
      - 'State' # State consists on many
      - 'Resources' # Resources consists 5 different resource types
  TooManyStatements:
    exclude:
      - 'SetupGame#validate' # validation should be in one method, it can make a long statement
      - 'State#initialize' # state contains many attributes which need to be initialized
