detectors:
  IrresponsibleModule:
    enabled: false
  Attribute:
    exclude:
      - 'State' # State is to be operated on
      - 'Resources' # Needed to do clever meta-programming
  TooManyInstanceVariables:
    exclude:
    - 'State' # State consists on many
    - 'Resources' # Resources consists of 5 different resource types
