Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - 'lib/catan/helpers/map_geometry.rb' # MapGeometry must contain long multi-line constants

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/catan/serializers/game_serializer.rb' # this methid doesn't congruent here

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ╲
    - ╱
