Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'lib/catan/helpers/map_geometry.rb' #MapGeometry must contain long multi-line constants

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ╲
    - ╱
