Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - 'lib/catan/helpers/map_geometry.rb' # MapGeometry must contain long multi-line constants

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/catan/serializers/game_serializer.rb' # this metric doesn't congruent

Metrics/AbcSize:
  Exclude:
    - 'lib/catan/serializers/game_serializer.rb' # this metric doesn't congruent
    - 'lib/catan/serializers/game_deserializer.rb' # this metric doesn't congruent
    - 'lib/catan/interactors/buy_settlement.rb' # disagreed

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ╲
    - ╱

Style/BlockDelimiters:
  Exclude:
    - 'spec/helpers/score_calculator_spec.rb' # Ruby does not allow one-line multi {}-syntax
