Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'lib/catan/helpers/map_geometry.rb' # MapGeometry must contain long multi-line constants

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/catan/interactors/settle_with_road.rb' # temporary

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ╲
    - ╱
